name: little-turtle

services:
  story-bot:
    image: ghcr.io/pkarpovich/little-turtle:latest
    container_name: story-bot
    restart: unless-stopped
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_PHONE_NUMBER: ${TELEGRAM_PHONE_NUMBER}
      TELEGRAM_ALLOWED_USERS: ${TELEGRAM_ALLOWED_USERS}
      USER_IDS_TO_SEND_MORNING_MSG: ${USER_IDS_TO_SEND_MORNING_MSG}
      CHAT_IDS_TO_SEND_STORIES: ${CHAT_IDS_TO_SEND_STORIES}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      TNL_API_KEY: ${TNL_API_KEY}
      ERROR_HANDLER_ENABLED: ${ERROR_HANDLER_ENABLED}
      ERROR_HANDLER_DNS: ${ERROR_HANDLER_DNS}
      ERROR_HANDLER_ENVIRONMENT: ${ERROR_HANDLER_ENVIRONMENT}
      ERROR_HANDLER_SERVER_NAME: ${ERROR_HANDLER_SERVER_NAME}
    volumes:
      - ./little_turtle/services/little_turtle.session:/app/little_turtle/services/little_turtle.session
      - story-images:/app/little_turtle/images
    depends_on:
      - story-store
      - langfuse-server

  story-store:
    container_name: story-store
    image: mongo:4.4-bionic
    ports:
      - 27666:27017
    expose:
      - 27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - story-store-data:/data/db

  story-cache:
    container_name: story-cache
    image: redis:7.0.2-alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  langfuse-server:
    image: ghcr.io/langfuse/langfuse:latest
    depends_on:
      - langfuse-db
    ports:
      - 33600:3000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${LF_DB_URL:-postgres://langfuse_admin:langfuse@langfuse-db:5432/langfuse}
      - NEXTAUTH_SECRET=${LF_NEXTAUTH_SECRET:-mysecret}
      - SALT=${LF_SALT:-mysalt}
      - NEXTAUTH_URL=${LF_NEXTAUTH_URL:-http://localhost:33600}
      - TELEMETRY_ENABLED=false
      - NEXT_PUBLIC_SIGN_UP_DISABLED=false
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=true

  langfuse-db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${LF_DB_USER:-langfuse_admin}
      - POSTGRES_PASSWORD=${LF_DB_PASSWORD:-langfuse}
      - POSTGRES_DB=${LF_DB_NAME:-langfuse}
    volumes:
      - langfuse-db-data:/var/lib/postgresql/data

volumes:
  story-store-data:
  story-images:
  langfuse-db-data: