name: little-turtle

services:
  story-bot:
    image: ghcr.io/pkarpovich/little-turtle:latest
    container_name: story-bot
    restart: unless-stopped
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_PHONE_NUMBER: ${TELEGRAM_PHONE_NUMBER}
      TELEGRAM_ALLOWED_USERS: ${TELEGRAM_ALLOWED_USERS}
      USER_IDS_TO_SEND_MORNING_MSG: ${USER_IDS_TO_SEND_MORNING_MSG}
      CHAT_IDS_TO_SEND_STORIES: ${CHAT_IDS_TO_SEND_STORIES}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      TNL_API_KEY: ${TNL_API_KEY}
      ERROR_HANDLER_ENABLED: ${ERROR_HANDLER_ENABLED}
      ERROR_HANDLER_DNS: ${ERROR_HANDLER_DNS}
      ERROR_HANDLER_ENVIRONMENT: ${ERROR_HANDLER_ENVIRONMENT}
      ERROR_HANDLER_SERVER_NAME: ${ERROR_HANDLER_SERVER_NAME}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_URL: ${LANGFUSE_URL}
    volumes:
      - ./little_turtle/services/little_turtle.session:/app/little_turtle/services/little_turtle.session
      - story-images:/app/little_turtle/images
    depends_on:
      - story-store

  story-store:
    container_name: story-store
    image: mongo:4.4-bionic
    ports:
      - 27666:27017
    expose:
      - 27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - story-store-data:/data/db

  story-cache:
    container_name: story-cache
    image: redis:7.0.2-alpine
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  story-store-data:
  story-images:
  langfuse-db-data: