name: little-turtle

services:
  story-bot:
    #    image: ghcr.io/pkarpovich/little-turtle:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: story-bot
    restart: unless-stopped
    environment:
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      ANTHROPIC_MODEL: ${ANTHROPIC_MODEL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_PHONE_NUMBER: ${TELEGRAM_PHONE_NUMBER}
      TELEGRAM_ALLOWED_USERS: ${TELEGRAM_ALLOWED_USERS}
      USER_IDS_TO_SEND_MORNING_MSG: ${USER_IDS_TO_SEND_MORNING_MSG}
      CHAT_IDS_TO_SEND_STORIES: ${CHAT_IDS_TO_SEND_STORIES}
      PHOENIX_COLLECTOR_ENDPOINT: http://phoenix:6006
      REDIS_URL: redis://story-cache:6379/0
    networks:
      - telemetry
    volumes:
      - ./little_turtle/services/little_turtle.session:/app/little_turtle/services/little_turtle.session
      - story-images:/app/little_turtle/images
    depends_on:
      - story-cache

  story-cache:
    container_name: story-cache
    image: redis:7.0.2-alpine
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  story-images:
  langfuse-db-data:

networks:
  telemetry:
    external: true