name: little-turtle

services:
  story-store:
    image: mongo:7.0
    ports:
      - 27017:27017
    expose:
      - 27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - story-store-data:/data/db

volumes:
  story-store-data: