[tool.poetry]
name = "little-turtle"
version = "0.1.0"
description = ""
authors = ["Pavel Karpovich <pavel.karpovich@outlook.com>"]
readme = "README.md"
packages = [{include = "little_turtle"}]

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.0.286"
python-dotenv = "^1.0.0"
openai = "^0.28.0"
telethon = "^1.30.0"
pymongo = "^4.5.0"
dependency-injector = "^4.41.0"
midjourney-api = "^1.0.7"
aiogram = "3.0.0"
structlog = "^23.1.0"
sentry-sdk = "^1.30.0"
apscheduler = "^3.10.4"
redis = "^5.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
