[tool.poetry]
name = "little-turtle"
version = "0.1.0"
description = ""
authors = ["Pavel Karpovich <pavel.karpovich@outlook.com>"]
readme = "README.md"
packages = [{include = "little_turtle"}]

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.0.343"
python-dotenv = "^1.0.0"
openai = "^1.3.6"
telethon = "^1.32.1"
pymongo = "^4.6.1"
dependency-injector = "^4.41.0"
midjourney-api = "^1.0.7"
aiogram = "^3.2.0"
structlog = "^23.2.0"
sentry-sdk = "^1.38.0"
apscheduler = "^3.10.4"
redis = "^5.0.1"
jinja2 = "^3.1.2"
langfuse = "^2.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
