[tool.poetry]
name = "little-turtle"
version = "0.1.0"
description = ""
authors = ["Pavel Karpovich <pavel.karpovich@outlook.com>"]
readme = "README.md"
packages = [{ include = "little_turtle" }]

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.1.16"
python-dotenv = "^1.0.1"
openai = "^1.23.2"
telethon = "^1.34.0"
dependency-injector = "^4.41.0"
aiogram = "^3.4.1"
structlog = "^24.1.0"
sentry-sdk = "^1.45.0"
apscheduler = "^3.10.4"
redis = "^5.0.3"
jinja2 = "^3.1.3"
langfuse = "^2.27.0"
langchain-openai = "^0.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
