[tool.poetry]
name = "little-turtle"
version = "0.1.0"
description = ""
authors = ["Pavel Karpovich <pavel.karpovich@outlook.com>"]
readme = "README.md"
packages = [{include = "little_turtle"}]

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.0.268"
python-dotenv = "^1.0.0"
openai = "^0.27.8"
telethon = "^1.29.3"
pymongo = "^4.4.1"
pytelegrambotapi = "^4.13.0"
dependency-injector = "^4.41.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
